package com.example.modelo;
// Generated 23 feb 2023 11:07:05 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Shows generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "netflix")
public class Usuarios implements java.io.Serializable {

	private String correo;
	private String contrasegna;

	public Usuarios() {
	}

	public Usuarios(String nombre, String contrasegna) {
		this.correo = nombre;
		this.contrasegna = contrasegna;
	}

	@Id
	@Column(name = "correo", unique = true, nullable = false)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}
	
	@Column(name = "contrasegna", nullable = false)
	public String getContrasegna() {
		return contrasegna;
	}

	public void setContrasegna(String contrasegna) {
		this.contrasegna = contrasegna;
	}

}
